<?php
namespace TDW\IO\Core;

class ScrapeCore extends \DOMDocument {

    function __construct($version, $encoding)
    {
        parent::__construct($version, $encoding);
    }

    function loadHTMLFile($filename)
    {
        parent::loadHTMLFile($filename); // TODO: Change the autogenerated stub
    }


}